### ISSUE TITLE
Omit namespace and class from method names

### ISSUE THREAD

**Issue by peastman** [rmcgibbo/sphinxcontrib-autodoc_doxygen#8]
I did this by changing line 134 of autodoc.py from

```
return (rtype and (rtype + ' ') or '') + self.modname + '::' + self.objpath
```

to

```
return (rtype and (rtype + ' ') or '') + self.objpath
```

You mentioned before that this caused links to methods to be broken, but as far as I can tell it seems to work fine.

By the way, all the examples at https://rawgit.com/rmcgibbo/sphinxcontrib-autodoc_doxygen/gh-pages/autodoxyclass.html include the option `:members:`.  When I include that, I get the error message

```
ERROR: An option to autodoxyclass is either unknown or has an invalid value: 'members'
```

If I omit it, everything seems to work correctly.

**Comment by rmcgibbo** [comment]
- Sounds good with removing the classname from the members. Do you want to file a PR -- or I can change it. 
- For the `members`, I think you might not have updated to the latest git head?

**Comment by peastman** [comment]
I just updated to the latest code.  You've completely changed the implementation of `format_name()` and the change I made before now produces an exception.  So I think I'd better leave it to you.

**Comment by rmcgibbo** [comment]
Slightly broken https://rawgit.com/rmcgibbo/sphinxcontrib-autodoc_doxygen/gh-pages/generated/OpenMM::NonbondedForce.html#_CPPv2NK6OpenMM14NonbondedForce16getNumExceptionsEv
